go_coverage_profile ?= /tmp/.coverage.out

.PHONY: fmt vet build build-only clean test-clean test-verbose

fmt:
	go fmt ./...

vet:
	go vet ./...

build-only:
	go build ./...

build: vet build-only

clean:: test-clean
	go clean ./...

test-clean:
	go clean -testcache

test test-verbose: test-clean build
	go test $(if $(findstring verbose,$@),-v) -cover -coverprofile=$(go_coverage_profile) ./...
